PRAGMA foreign_keys=OFF;

DROP TABLE IF EXISTS OrderItem;
DROP TABLE IF EXISTS "Order";
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS StoreSetting;

CREATE TABLE Customer (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL UNIQUE,
  email TEXT,
  address TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE Product (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  defaultPrice INTEGER NOT NULL,
  note TEXT,
  icon TEXT NOT NULL DEFAULT 'Package',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE "Order" (
  id TEXT PRIMARY KEY NOT NULL,
  code TEXT NOT NULL UNIQUE,
  customerId TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PROCESSING',
  subtotal INTEGER NOT NULL,
  discount INTEGER NOT NULL DEFAULT 0,
  shippingFee INTEGER NOT NULL DEFAULT 0,
  tax INTEGER NOT NULL DEFAULT 0,
  total INTEGER NOT NULL,
  paymentMethod TEXT,
  shippingMethod TEXT,
  shippingAddress TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  CONSTRAINT Order_customerId_fkey FOREIGN KEY (customerId)
    REFERENCES Customer(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE OrderItem (
  id TEXT PRIMARY KEY NOT NULL,
  orderId TEXT NOT NULL,
  productId TEXT NOT NULL,
  name TEXT NOT NULL,
  detail TEXT,
  sku TEXT,
  quantity INTEGER NOT NULL,
  unitPrice INTEGER NOT NULL,
  CONSTRAINT OrderItem_orderId_fkey FOREIGN KEY (orderId)
    REFERENCES "Order"(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT OrderItem_productId_fkey FOREIGN KEY (productId)
    REFERENCES Product(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE StoreSetting (
  id TEXT PRIMARY KEY NOT NULL DEFAULT 'default',
  shopName TEXT NOT NULL,
  phone TEXT NOT NULL,
  paperSize TEXT NOT NULL DEFAULT 'A5',
  showBarcode BOOLEAN NOT NULL DEFAULT true,
  autoPrint BOOLEAN NOT NULL DEFAULT false,
  shippingUnits TEXT NOT NULL DEFAULT 'GHTK,GHN,Viettel Post',
  updatedAt DATETIME NOT NULL
);

PRAGMA foreign_keys=ON;
